export enum OTP_TYPE {
    LOGIN_OTP_PENDING = 'LOGIN_OTP_PENDING',
    REGISTER_OTP_PENDING = 'REGISTER_OTP_PENDING',
    LOGIN_OTP_VERIFIED = 'LOGIN_OTP_VERIFIED',
    REGISTER_OTP_VERIFIED = 'REGISTER_OTP_VERIFIED',
    FORGET_PASSWORD_OTP_PENDING = 'FORGET_PASSWORD_OTP_PENDING',
    FORGET_PASSWORD_OTP_VERIFIED = 'FORGET_PASSWORD_OTP_VERIFIED'
  }