export enum USER_ROLE_ENUM {
    ADMIN = 'ADMIN',
    USER = 'USER',
    SUB_ADMIN= 'SUB_ADMIN'
  }


export enum USER_STATUS_ENUM {
    REGISTRATION_OTP_VERIFICATION_PENDING= 'REGISTRATION_OTP_VERIFICATION_PENDING',
    ADMIN_VERIFICATION_PENDING= 'ADMIN_VERIFICATION_PENDING',
    ACTIVE = 'ACTIVE',
    DEACTIVATED = 'DEACTIVATED'
  }